name: CI

# Trigger the workflow on push to master / main, or on pull request
on:
  push:
    branches:
      - master
      - main
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: "${{ matrix.gap-version }} | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        gap-version:
          - master # TODO: replace by devel?
          - v4.15.0-beta1
          - v4.14
          - v4.13
          - v4.12
          - v4.11
          - v4.10

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-cygwin@v2
        if: ${{ runner.os == 'Windows' }}
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@main # TODO: replace by v2
      - uses: gap-actions/run-pkg-tests@main # TODO: replace by v4
      - uses: gap-actions/run-pkg-tests@main # TODO: replace by v4
        with:
          mode: onlyneeded
      - uses: gap-actions/process-coverage@main # TODO: replace by v3
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
